# Generated by Django 5.0 on 2025-11-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('carrera', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('carrera', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], max_length=20)),
            ],
        ),
    ]
