# Generated by Django 5.0 on 2025-11-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
