# Generated by Django 5.0 on 2025-11-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0003_estudiante_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
