# Generated by Django 5.0 on 2025-11-14 02:26

import app_lib.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0004_alter_docente_correo_alter_estudiante_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=50, null=True)),
                ('carrera', models.TextField(blank=True, max_length=15, null=True)),
                ('asignatura', models.TextField(blank=True, max_length=15, null=True)),
                ('archivo', models.FileField(upload_to=app_lib.models.ruta_subida_apuntes)),
                ('imagen', models.ImageField(default='default_apunte.jpg', upload_to=app_lib.models.ruta_subida_imagen)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.RenameModel(
            old_name='Docente',
            new_name='Usuario',
        ),
        migrations.AddField(
            model_name='apunte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lib.usuario'),
        ),
    ]
