# Generated by Django 5.0 on 2025-11-14 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0006_remove_usuario_correo_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
