# Generated by Django 5.0 on 2025-11-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0007_remove_usuario_apellido_remove_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ApunteCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartido', models.DateTimeField(auto_now_add=True)),
                ('apunte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lib.apunte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lib.usuario')),
            ],
            options={
                'unique_together': {('apunte', 'usuario')},
            },
        ),
    ]
