# Generated by Django 5.0 on 2025-11-18 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0008_alter_apunte_descripcion_apuntecompartido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApunteCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('apunte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lib.apunte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lib.usuario')),
            ],
            options={
                'unique_together': {('apunte', 'usuario')},
            },
        ),
    ]
